spring.application.name=ecommerce-cloud

#Configuracao com a base de dados mysql
spring.datasource.url=jdbc:mysql://localhost/ibmec-cloud-mall
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Configuracao do Cosmos DB
azure.cosmos.uri=https://localhost:8081/
azure.cosmos.key=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
azure.cosmos.database=ibmec-cloud-mall-products
azure.cosmos.queryMetricsEnabled=true
azure.cosmos.responseDiagnosticsEnabled=true