spring.application.name=ecommerce-cloud

#Configuracao com a base de dados mysql
spring.datasource.url=jdbc:mysql://localhost:3306/ibmec-cloud-mall
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Configuracao do Cosmos DB
azure.cosmos.uri=https://ibmec-produtos-database.documents.azure.com:443/
azure.cosmos.key=i6z0EXMSFoss84VipDU7ITJtCwakWUYUsI8k8uqQMoc14BfLv6yRc6m9yt2bse871RXgj0R4tQK8ACDbbNUnDg==
azure.cosmos.database=ibmec-cloud-products
azure.cosmos.queryMetricsEnabled=true
azure.cosmos.responseDiagnosticsEnabled=true 